---
title: "salaries_gov_epi"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include=FALSE}
library(tidyverse)
library(readr)
library(kableExtra)
library(ggplot2)
library(reactable)
library(DT)
library(plotly)
library(readxl)
```

```{r, echo=FALSE, include=FALSE}
#coli data from kaggle
coli <- read.csv("data/cost_of_living_missouri_economic_research_and_information_center.csv") 
salary <- read.csv("data/oes_research_2022_allsectors_trimmed.csv")
#salary <- read_excel("data/oes_research_2022_allsectors_abbr.xlsx", sheet=1)
#states data from https://developers.google.com/public-data/docs/canonical/states_csv
states <- read.csv("data/states.csv")
```

```{r, echo=FALSE, include=FALSE}
salary_clean <- salary %>% 
  rename_with( ~ tolower(gsub(" ", "", .x, fixed = TRUE))) %>%
  select(area, area_title, naics, naics_title, occ_title, tot_emp, a_mean) %>%
  rename(name = area_title)
```

```{r, echo=FALSE, include=FALSE}

salary_clean$a_mean <- as.numeric(salary_clean$a_mean)
salary_clean$tot_emp <- as.integer(salary_clean$tot_emp)
#for expedience, I decided to drop NAs for now. 
salary_clean <- salary_clean %>% drop_na()

```

```{r, echo=FALSE, include=FALSE}
coli_clean <- coli %>% 
  rename_with( ~ tolower(gsub(" ", "", .x, fixed = TRUE))) %>%
  select(state, conversion) %>%
  mutate(conversion_adj = conversion/100)

#remove non-US states
coli_clean <- coli_clean[!(coli_clean$state == "Remote" |
                             coli_clean$state == "British Columbia"|
                             coli_clean$state == "Ontario"),]
  
```

```{r, echo=FALSE, include=FALSE}
#join the 3 datasets 
salary_joined <- salary_clean %>%
  left_join(states, by = "name")%>%
  left_join(coli_clean, by = "state") 
```

```{r, echo=FALSE, include=FALSE}
#add an adjusted salary, weighted by the cost of living index

salary_joined_adj <- salary_joined %>% 
  group_by(name, naics, naics_title, occ_title) %>%
  mutate(adjusted_sal = (a_mean * (1+(1-(conversion/100) )))) %>%
  arrange(name, naics, naics_title, occ_title)
```

```{r, echo=FALSE, include=FALSE}
#just epidemiologists
salary_epis <- salary_joined_adj %>% 
  filter(occ_title == "Epidemiologists")
```

```{r, echo=FALSE, include=FALSE}
#what are number of jobs available by state?
#in what state do you have the most jobs and also the most pay for epidemiologists?
#for example, New Jersey is fairly high on the list in terms of income and also high # of jobs (11 out of 54 - includes Puerto Rico, Guam, US Virgin Islands, and Washington DC)
#assign each state a # between 1 and 54 for their income level & another assign # for their job availability
jobs_by_state <- salary_epis %>% 
  group_by(name) %>% 
  summarize(tot_jobs = sum(tot_emp),
            avg_pay = round(mean(a_mean),2)) %>% 
  mutate(rank_most_jobs = percent_rank(tot_jobs),
         most_jobs = ifelse(rank_most_jobs >= 0.75, 1, 0),
         rank_most_pay = (percent_rank(avg_pay)),
         most_pay = ifelse(rank_most_pay >= 0.75, 1,0),
         best_both = ifelse(most_jobs == 1 & most_pay == 1, 1, 0)
         ) %>%
  arrange(desc(best_both), desc(most_pay))

jobs_by_state_table <- jobs_by_state %>%
  select(name, tot_jobs, avg_pay, rank_most_jobs, rank_most_pay, best_both)
```

```{r, echo=FALSE}
plot1 <- jobs_by_state %>% 
  ggplot(aes(x=tot_jobs, y=avg_pay, label=name)) +
  geom_point()+
  
  geom_abline(intercept=72198.52859, slope=12.25004, color="blue")+
  #geom_smooth(method = "lm", se = FALSE)+
  labs(x="Number of persons employed as epidemiologists, May 2022", y="Average adjusted annual wage ($US)", caption = "Data source: U.S. Bureau of Labor Statistics")+
  theme_bw()
```

```{r, echo=FALSE, include=FALSE}
#calculate intercept/slope
coef(lm(avg_pay~tot_jobs, data=jobs_by_state))
#72198.53
#12.25
cor(jobs_by_state$tot_jobs, jobs_by_state$avg_pay)
#0.3865659
```

```{r, echo=FALSE}
ggplotly(plot1)
```


```{r, echo=FALSE}
jobs_by_state_gov <- salary_epis %>% 
  filter(naics == 99) %>%
  group_by(name) %>% 
  summarize(tot_jobs = sum(tot_emp),
            avg_pay = round(mean(a_mean),2)) %>% 
  mutate(rank_most_jobs = percent_rank(tot_jobs),
         most_jobs = ifelse(rank_most_jobs >= 0.75, 1, 0),
         rank_most_pay = (percent_rank(avg_pay)),
         most_pay = ifelse(rank_most_pay >= 0.75, 1,0),
         best_both = ifelse(most_jobs == 1 & most_pay == 1, 1, 0)
         ) %>%
  arrange(desc(best_both), desc(most_pay))
```

```{r, echo=FALSE, include=FALSE}
#calculate intercept/slope
coef(lm(avg_pay~tot_jobs, data=jobs_by_state_gov))
#67204.27266
#26.59695
cor(jobs_by_state_gov$tot_jobs, jobs_by_state_gov$avg_pay)
#0.3121284
```

```{r}
plot2<- jobs_by_state_gov %>% 
  ggplot(aes(x=tot_jobs, y=avg_pay, label=name)) +
  geom_point()+
   geom_abline(intercept=67204.27266, slope=26.59695, color="blue")+
  
  labs(x="Number of persons employed as federal/national/state epidemiologists, May 2022", y="Average adjusted annual wage ($US)", caption = "Data source: U.S. Bureau of Labor Statistics")+
  theme_bw()

ggplotly(plot2)
```