---
title: "Labor - Analysis of Epidemiology Salaries"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(kableExtra)
library(ggplot2)
library(reactable)
```

```{r}
#coli data from kaggle
coli <- read.csv("data/cost_of_living_missouri_economic_research_and_information_center.csv") 
salary <- read.csv("data/oes_research_2022_allsectors_abbr.csv")
#states data from https://developers.google.com/public-data/docs/canonical/states_csv
states <- read.csv("data/states.csv")
```

```{r}
salary_clean <- salary %>% 
  rename_with( ~ tolower(gsub(" ", "", .x, fixed = TRUE))) %>%
  select(area, area_title, naics, naics_title, occ_title, tot_emp, a_mean) %>%
  rename(name = area_title)
 

salary_clean$a_mean <- as.numeric(salary_clean$a_mean)
salary_clean$tot_emp <- as.integer(salary_clean$tot_emp)
#for expedience, I decided to drop NAs for now. Might review them at another time
salary_clean <- salary_clean %>% drop_na()

```

```{r}
coli_clean <- coli %>% 
  rename_with( ~ tolower(gsub(" ", "", .x, fixed = TRUE))) %>%
  select(state, conversion) %>%
  mutate(conversion_adj = conversion/100)

#remove non-US states
coli_clean <- coli_clean[!(coli_clean$state == "Remote" |
                             coli_clean$state == "British Columbia"|
                             coli_clean$state == "Ontario"),]
  
```

```{r}
#join the 3 datasets 
salary_joined <- salary_clean %>%
  left_join(states, by = "name")%>%
  left_join(coli_clean, by = "state") 
```


```{r}
#add an adjusted salary, weighted by the cost of living index

salary_joined_adj <- salary_joined %>% 
  group_by(name, naics, naics_title, occ_title) %>%
  mutate(adjusted_sal = (a_mean * (1+(1-(conversion/100) )))) %>%
  arrange(name, naics, naics_title, occ_title)
  
                         
```

```{r}
#just epidemiologists

salary_epis <- salary_joined_adj %>% 
  filter(occ_title == "Epidemiologists")
```


```{r}
#Table of epi salaries by NAICS group with adjusted salaries
epi_job_groups_table <- salary_epis %>%
  group_by(naics_title) %>%
  summarize(mean_adj_income = mean(adjusted_sal)) %>% 
  arrange(desc(mean_adj_income))
  
kable(epi_job_groups_table,
      booktabs = T,
      col.names = c("Group title", "Mean adjusted annual income"),
      caption = "Mean adjusted income by group for Epidemiologists (adjusted by cost of living)") %>%
  kable_styling(full_width = F)
```

```{r}
#table of jobs by group title

epi_jobs_num_table <- salary_epis %>%
  group_by(naics_title) %>% 
  summarize(num_jobs = sum(tot_emp)) %>% 
  arrange(desc(num_jobs))

epi_jobs_num_table <- data.frame(epi_jobs_num_table) 
epi_jobs_num_table$naics_title <- as.factor(epi_jobs_num_table$naics_title)

kable(epi_jobs_num_table,
      booktabs = T,
      col.names = c("Group title", "Number of jobs"),
      caption = "Number of epidemiologist jobs by NAICS group") %>%
  kable_styling(full_width = F)
```

```{r}
#barchart 
epi_jobs_num_table %>% 
  
ggplot(aes(x = reorder(naics_title, num_jobs), y = num_jobs, fill=naics_title)) + 
  geom_col() +
  scale_x_discrete(label=function(x) stringr::str_trunc(x, 20))+
  labs(x = "", y = "", title = "Total number of jobs in Epidemiology (2022) by NAICS group")+
  theme(axis.text.x = element_text(size = 8, angle = 45, hjust = 1, vjust = 0.9),
        legend.position="none")

```

```{r}
#what are number of jobs available by state?
#in what state do you have the most jobs and also the most pay for epidemiologists?
#for example, New Jersey is fairly high on the list in terms of income and also high # of jobs (11 out of 54 - includes Puerto Rico, Guam, US Virgin Islands, and Washington DC)
#assign each state a # between 1 and 54 for their income level & another assign # for their job availability
jobs_by_state <- salary_epis %>% 
  group_by(name) %>% 
  summarize(tot_jobs = sum(tot_emp),
            avg_pay = round(mean(a_mean),2)) %>% 
  mutate(rank_most_jobs = percent_rank(tot_jobs),
         most_jobs = ifelse(rank_most_jobs >= 0.75, 1, 0),
         rank_most_pay = percent_rank(avg_pay),
         most_pay = ifelse(rank_most_pay >= 0.75, 1,0),
         best_both = ifelse(most_jobs == 1 & most_pay == 1, 1, 0)
         ) %>% 
  arrange(desc(best_both), desc(most_pay))
reactable(jobs_by_state)
```





